name: DotNet SDK publish
description: DotNet SDKs publish action

runs:
  using: composite
  steps:
    - name: Semaphore
      uses: ./.github/actions/semaphore
      with:
        name: dotnet-publish
    - name: Publish
      if: success()
      shell: bash
      run: |
        dotnet nuget push ./dotnet/PackagesOutput/*.nupkg --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY --skip-duplicate
        echo "Succesfully published DotNet SDKs"
      env:
        NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
