name: NPM Publish

description: Publish a package to NPM

inputs:
  working-directory:
    description: the path to the directory from repository root
    type: string
    required: true

runs:
  using: composite
  steps:
    - name: Publish
      id: publish
      shell: bash
      working-directory: ${{inputs.working-directory}}
      run: |
        echo "::group::Installing and updating dependencies"
        yarn --cwd ../../ install
        yarn install
        npm run deps --if-present -- --commit
        echo "::endgroup::"

        if [ "${{inputs.skip-build}}" = "false" ]
        then
          echo "::group::Building package"
          npm run build --if-present
          echo "::endgroup::"
        fi

        echo "::group::Publish $PACKAGE_NAME"
        if [ "${{inputs.skip-npm}}" = "true" ]
        then yarn version "--${{inputs.version}}"
        elif [ ! -z "${{inputs.version}}" ]
        then yarn publish "--${{inputs.version}}"
        else yarn publish
        fi
        TAG="$(git describe --tags --abbrev=0 || true)"
        if [ ! -z "$TAG" ]
        then 
          echo "::notice::Publish tag - $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
        fi

        CHANGELOG="$(yarn --silent -p @applitools/bongo bongo log --latest-changelog)"
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

        echo "## $TAG" >> $GITHUB_STEP_SUMMARY
        echo "$CHANGELOG" >> $GITHUB_STEP_SUMMARY
        echo "::endgroup::"

        echo "::group::Merge publish branch into ${{github.ref_name}}"
        git checkout ${{github.ref_name}}
        git fetch
        git status
        git pull origin ${{github.ref_name}} --rebase
        git merge $BRANCH
        git push origin ${{github.ref_name}}
        echo "::endgroup::"
