name: Queue

inputs:
  name:
    description: name of the queue
    type: string
  max-parallel:
    description: max number of parallel jobs to run for the queue
    type: number
  token:
    description: github access token
    default: ${{github.token}}

runs:
  using: node16
  main: dist/index.js
  post: dist/index.js
