name: Generic
description: Generic coverage tests
inputs:
  working-directory:
    description: the path to the directory from repository root
    type: string
    required: true
  config:
    description: path to the configuration file (local or remote)
    type: string
  suite:
    description: suite name
    type: string
  shell:
    description: shell to use
    type: string
    default: bash

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
        registry-url: https://registry.npmjs.org
    - name: Generating tests
      working-directory: ${{inputs.working-directory}}
      shell: ${{inputs.shell}}
      run: |
        export NODE_AUTH_TOKEN=$NPM_AUTH_TOKEN
        echo token=$NODE_AUTH_TOKEN
        npx --package=@applitools/generic@latest --yes -- 'NODE_OPTIONS=$(echo --experimental-import-meta-resolve --experimental-loader=$(NODE_PATH=$(echo $PATH | sed "s/.bin.*//") node -pe "require.resolve(\"@applitools/generic/dist/code-loader.js\")")) generic "${{inputs.config}}" --suite="${{inputs.suite}}"'

