name: Publish
description: Publish a package to NPM
inputs:
  working-directory:
    description: the path to the directory from repository root
    type: string
    required: true
  version:
    description: version type (patch, major, minor)
    type: string
    default: patch
  skip-npm:
    description: should the package be published in npm
    type: boolean
    default: false
outputs:
  tag:
    description: name of the tag pushed after publishing
    value: ${{steps.publish.outputs.tag}}

runs:
  using: composite
  steps:
    - id: publish
      shell: bash
      working-directory: ${{inputs.working-directory}}
      run: |
        echo "::group::Prepare package"
        if [ ! -z "${{inputs.dirname}}" ]; then cd ${{github.workspace}}/${{inputs.dirname}}; fi
        PACKAGE_NAME="$(node -e "console.log(require('./package.json').name)")"
        echo "::endgroup::"

        echo "::group::Configure Git"
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        TEMP_BRANCH="${PACKAGE_NAME}_$(date +%F_%H-%M)"
        git checkout -b $TEMP_BRANCH
        git push -u origin $TEMP_BRANCH
        echo "::notice::Publish branch - $TEMP_BRANCH"
        echo "::endgroup::"

        echo "::group::Installing and updating dependencies"
        yarn install
        npm run deps --if-present -- --commit
        echo "::endgroup::"

        echo "::group::Building package"
        npm run build --if-present
        echo "::endgroup::"

        echo "::group::Publish $PACKAGE_NAME"
        if [ "${{inputs.skip-npm}}" = "false" ]; then yarn publish "--${{inputs.version}}"; else yarn version "--${{inputs.version}}"; fi
        TAG="$(git describe --tags --abbrev=0)"
        echo "::notice::Publish tag - $TAG"
        echo "::set-output name=tag::$TAG"
        echo "::endgroup::"

        echo "::group::Merge publish branch into ${{github.ref_name}}"
        git checkout ${{github.ref_name}}
        git status
        git pull origin ${{github.ref_name}} --rebase
        git merge $TEMP_BRANCH
        git push origin ${{github.ref_name}}
        echo "::endgroup::"
