name: Parser

inputs:
  packages:
    description: list of package names (aliases) with modifiers such as version or aut protocol
    type: string
    required: true
  allow-variations:
    description: whether modifiers should be allowed to create variations (wdio:cdp or selenium@3)
    type: boolean
    default: false
  allow-cascading:
    description: whether including of not listed packages should be allowed
    type: boolean
    default: false
  only-changed:
    description: whether including of not changed since last release packages should be allowed
    type: boolean
    default: false
  release-version:
    description: default release version type (major, minor, patch)
    type: string
outputs:
  packages:
    description: map or array of each package or variation respectively
runs:
  using: node16
  main: dist/index.js
