name: Parser

inputs:
  packages:
    description: list of package names (aliases) with modifiers such as version or aut protocol
    type: string
    required: true
  env:
    description: list of environment variables to add to every job
    type: string
    required: false
  allow-variations:
    description: whether modifiers should be allowed to create variations (wdio+cdp or selenium@3)
    type: boolean
    default: false
  include-only-changed:
    description: whether including of not changed since last version packages should be allowed
    type: boolean
    default: false
  include-dependencies:
    description: whether dependencies of the target packages should be targeted as well
    type: boolean
    default: false
  link-dependencies:
    description: whether dependencies of the target packages should be linked
    type: boolean
    default: false
  default-publish-version:
    description: default publish version type (major, minor, patch)
    type: string
outputs:
  packages:
    description: map or array of each package or variation respectively
runs:
  using: node16
  main: dist/index.js
