name: "DotNet - Deploy"

on:
  workflow_dispatch:
     inputs:
      run_tests:
        description: Run tests
        type: boolean
        required: false
        default: true

env:
  DRIVER_PATH: /usr/bin
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  APPLITOOLS_API_KEY_READ: ${{ secrets.APPLITOOLS_API_KEY_READ }}
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
  GITHUB_TOKEN: ${{ secrets.RUN_GITHUB_TOKEN }}
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

jobs:
  update_cores:
    runs-on: ubuntu-latest
    outputs:
      release_branch: ${{steps.create_release_branch.outputs.release_branch}}
      new_tags: ${{steps.update_versions.outputs.new_tags}}
      packages_matrix: ${{steps.update_versions.outputs.packages_matrix}}
      core_version: ${{steps.update_versions.outputs.core_version}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Update versions
        id: update_versions
        shell: bash
        run: |
          cd dotnet
          export CORE_VERSION=$(../scripts/download-core-bin.sh --output version)
          mkdir -p ./Eyes.Image.Core.DotNet/runtimes/linux-alpine/native/
          mkdir -p ./Eyes.Image.Core.DotNet/runtimes/linux-x64/native/
          mkdir -p ./Eyes.Image.Core.DotNet/runtimes/linux-arm64/native/
          mkdir -p ./Eyes.Image.Core.DotNet/runtimes/osx-x64/native/
          mkdir -p ./Eyes.Image.Core.DotNet/runtimes/win-x64/native/
          mv core-alpine Eyes.Image.Core.DotNet/runtimes/linux-alpine/native
          mv core-linux Eyes.Image.Core.DotNet/runtimes/linux-x64/native
          mv core-linux-arm64 Eyes.Image.Core.DotNet/runtimes/linux-arm64/native
          mv core-macos Eyes.Image.Core.DotNet/runtimes/osx-x64/native
          mv core-win.exe Eyes.Image.Core.DotNet/runtimes/win-x64/native
          python updateChangelogAndProjectFiles.py
          cat ./MATRIX.json
          echo "packages_matrix=$(cat ./MATRIX.json)" >> $GITHUB_OUTPUT
          echo "core_version=$CORE_VERSION" >> $GITHUB_OUTPUT
      - name: Set release branch
        shell: bash
        run: |
          RELEASE_BRANCH=PR_RELEASE_$GITHUB_SHA
          echo "release_branch=$RELEASE_BRANCH" >> $GITHUB_OUTPUT
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0"
      - name: Create nugets
        shell: bash
        run: |
          cd dotnet
          dotnet pack ./Eyes.Image.Core.DotNet/Eyes.Image.Core.DotNet.csproj
          dotnet pack ./Eyes.Images.DotNet/Eyes.Images.DotNet.csproj
          dotnet pack ./Eyes.Appium.DotNet/Eyes.Appium.DotNet.csproj
          dotnet pack ./Eyes.Appium2.DotNet/Eyes.Appium2.DotNet.csproj
          dotnet pack ./Eyes.Playwright.DotNet/Eyes.Playwright.DotNet.csproj
          dotnet pack ./Eyes.Selenium.DotNet/Eyes.Selenium.DotNet.csproj
          dotnet pack ./Eyes.Selenium4.DotNet/Eyes.Selenium4.DotNet.csproj
      - name: Store Nugets
        uses: actions/upload-artifact@v3
        with:
          name: Nugets
          path: dotnet/PackagesOutput
      - uses: actions/upload-artifact@v3
        with:
          name: PublishingFiles
          path: |
            dotnet/*.txt
            dotnet/*.json
            dotnet/Eyes.*/CHANGELOG.md
            dotnet/Eyes.*/Eyes.*.csproj

  # dummy:
  #   needs: [update_cores]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo ${{needs.update_cores.outputs.packages_matrix}}

  test:
    if: |
      !cancelled() &&
      ${{ inputs.run_tests }}
    needs: [update_cores]
    uses: ./.github/workflows/dotnet-tests.yml
    secrets: inherit
    with:
      ref: ${{needs.update_cores.outputs.release_branch}}
      cross_platform: false
      generic: true
      core_version: ${{ needs.update_cores.outputs.core_version }}
   
  test_nugets:
    if: |
      !cancelled() &&
      (needs.update_cores.result == 'success')
    needs: [update_cores]
    uses: ./.github/workflows/dotnet-platform-tests.yml
    secrets: inherit
    with:
      ref: ${{needs.update_cores.outputs.release_branch}}

  release:
    if: |
      !cancelled() &&
      (needs.test_nugets.result == 'success') &&
      (needs.test.result == 'success' || needs.test.result == 'skipped')
    needs: [test, test_nugets]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{needs.update_cores.outputs.release_branch}}
      - uses: actions/download-artifact@v3
        with:
          name: PublishingFiles
          path: dotnet
      - name: Update SCM
        id: create_release_branch
        shell: bash
        run: |
          cd dotnet
          RELEASE_BRANCH=PR_RELEASE_$GITHUB_SHA
          git config --local user.email "action-queue@applitools.com"
          git config --local user.name "queue-bot"
          git checkout -b $RELEASE_BRANCH
          git add .
          git commit -m 'Updated changelogs and bumped versions.'
          git push origin HEAD:$RELEASE_BRANCH
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0"
      - uses: actions/download-artifact@v3
        with:
          name: Nugets
          path: dotnet/PackagesOutput
      - name: Upload nugets
        shell: bash
        run: |
          cd dotnet
          echo "will upload nugets"
          ls ./PackagesOutput/*.nupkg
          dotnet nuget push ./PackagesOutput/*.nupkg --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY --skip-duplicate
      - name: Create PR
        shell: bash
        run: |
          cd dotnet
          echo "will create PR"
          hub pull-request -h "PR_RELEASE_$GITHUB_SHA" -F NEW_TAGS.txt
    
  report_test_results:
    if: |
      !cancelled() &&
      (needs.release.result == 'success') &&
      (needs.test.result == 'success')
    needs: [test, release, update_cores]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.update_cores.outputs.packages_matrix) }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{needs.update_cores.outputs.release_branch}}
      - uses: actions/download-artifact@v3
        with:
          name: PublishingFiles
          path: dotnet
      - uses: actions/download-artifact@v3
        with:
          name: test-report
          path: dotnet
      - name: Sending report
        uses: ./.github/actions/bongo
        with:
          working-directory: dotnet
          shell: bash
          command: report
          report-id: dotnet_${{ matrix.name }}_$GITHUB_SHA
          name: dotnet_${{ matrix.name }}
          group: ${{matrix.group}}
          result-path: ${{matrix.report}}
          meta-path: meta-${{matrix.name}}.json

  release_report:
    if: |
      !cancelled() &&
      (needs.report_test_results.result == 'success' || needs.report_test_results.result == 'skipped')
    needs: [report_test_results, update_cores]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.update_cores.outputs.packages_matrix) }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{needs.update_cores.outputs.release_branch}}
      - uses: actions/download-artifact@v3
        with:
          name: PublishingFiles
          path: dotnet
      - name: Sending notification
        uses: ./.github/actions/bongo
        with:
          working-directory: dotnet
          shell: bash
          command: notification
          report-id: dotnet_${{ matrix.name }}_$GITHUB_SHA
          name: dotnet_${{ matrix.name }}
          release-version: ${{ matrix.version }}

