name: Publish - snippets

on:
  workflow_dispatch:
    inputs:
      version:
        description: version type
        type: choice
        options: [patch, minor, major]
        default: patch
        required: false
  workflow_call:
    inputs:
      version:
        description: version type
        type: string
        default: patch
        required: false
    secrets:
      NPM_TOKEN:
        required: true
      SAUCE_USERNAME:
        required: true
      SAUCE_ACCESS_KEY:
        required: true
env:
  CVG_TESTS_REMOTE: http://localhost:4444/wd/hub
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  FORCE_COLOR: 3
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          package: snippets
  publish:
    needs: [test]
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Publish to NPM
        uses: ./.github/actions/publish
        with:
          package: snippets
          version: ${{inputs.version || github.event.inputs.version}}
