name: Publish - sdk storybook

on:
  workflow_dispatch:
    inputs:
      version:
        description: version type
        type: choice
        options: [patch, minor, major]
        default: patch
      multienv:
        description: test on multiple environments
        type: boolean
        default: true
  workflow_call:
    inputs:
      version:
        description: version type
        type: string
        default: patch
    secrets:
      NPM_TOKEN:
        required: true
      APPLITOOLS_API_KEY:
        required: true
      APPLITOOLS_API_KEY_READ:
        required: true

env:
  FORCE_COLOR: 3
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY_JSSDK}}
  APPLITOOLS_API_KEY_READ: ${{secrets.APPLITOOLS_API_KEY_READ}}

jobs:
  verify:
    name: Verification
    runs-on: ubuntu-latest
    outputs:
      environments: ${{steps.prepare.outputs.environments}}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - name: Run pre-publish verifications
        shell: bash
        working-directory: ./js/packages/eyes-storybook
        run: |
          yarn install
          npx bongo release-pre-check --skip-deps --skip-commit --skip-verify-installed-versions
          npx bongo verify-changelog
      - name: Prepare environments
        id: prepare
        shell: bash
        run: |
          if [ ${{github.event.inputs.multienv}} = true ]
          then
            echo "::set-output name=environments::[{\"node-version\":16}, {\"node-version\":14}]"
          else
            echo "::set-output name=environments::[{\"node-version\":16}]"
          fi
  test:
    needs: [verify]
    strategy:
      max-parallel: 3
      matrix:
        include: ${{fromJSON(needs.verify.outputs.environments)}}
    name: 'Test (node: ${{matrix.node-version}})'
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          working-directory: ./js/packages/eyes-storybook
  test-versions:
    needs: [verify]
    strategy:
      matrix:
        storybook-version: ["5.0.0", "5.3.21", "6.3.12", "latest", "next"]
    name: 'Test (storybook: ${{matrix.storybook-version}})'
    runs-on: ubuntu-latest
    env:
      STORYBOOK_VERSION: ${{matrix.storybook-version}}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          working-directory: ./js/packages/eyes-storybook
          test-type: versions
  publish:
    needs: [test, test-versions]
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - name: Publish to NPM
        uses: ./.github/actions/publish
        with:
          working-directory: ./js/packages/eyes-storybook
          version: ${{inputs.version || github.event.inputs.version}}