name: Release please

on:
  push:
    branches:
      - chore/release-please

concurrency:
  group: ${{github.ref}}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Release please
    runs-on: ubuntu-latest
    outputs:
      packages: ${{steps.release.outputs.packages}}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Release please
        id: release
        uses: ./.github/actions/release-please
        with:
          token: ${{secrets.RUN_GITHUB_TOKEN}}
          branch: chore/release-please