on:
  push:
    branches:
      - chore/release-please

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - uses: ./.github/actions/release-please
        with:
          token: ${{secrets.RUN_GITHUB_TOKEN}}
          branch: chore/release-please