name: Release

run-name: Release (${{github.event.release.name}})

on:
  release:
    types: [published]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    # outputs:
    #   releases: ${{steps.setup.outputs.releases}}
    steps:
      - run: echo ${{toJSON(github.event.release)}}
      # - name: Check-out repository
      #   uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 0
      # - name: Setup
      #   uses: ./.github/actions/setup
      #   id: setup
      #   with:
      #     packages: changed
      #     ci: true