name: Test packages

run-name: ${{github.event_name == 'schedule' && 'Nightly' || ''}}

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches-ignore: ['dependabot/**', 'draft/**', 'play/**']
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      packages:
        description: package names (aliases and variations)
        type: string
        required: true
      test-type:
        description: testing type (unit, it, e2e, coverage, sanity)
        type: string
        required: false
      build-type:
        description: build type
        type: string
        required: false
      setup-type:
        description: setup type
        type: string
        required: false
      grep:
        description: test name pattern
        required: false
      links:
        description: package names to link
        required: false
      link-dependencies:
        description: use dependencies from source
        type: boolean
        default: false

concurrency: 
  group: ${{github.event_name == 'pull_request' && github.ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  DISPLAY: ':99'

jobs:
  setup:
    name: Setup
    if: ${{github.event_name == 'workflow_dispatch' || (github.actor != 'dependabot[bot]' && !github.event.pull_request.draft)}}
    runs-on: ubuntu-latest
    outputs:
      packages: ${{steps.setup.outputs.packages}}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/parser
        id: setup
        with:
          packages: ${{github.event.inputs.packages || (github.event_name == 'pull_request' && 'changed') || (github.event_name == 'schedule' && 'all')}}
          allow-variations: true
          link-dependencies: ${{github.event.inputs.link-dependencies || github.event_name == 'pull_request' || github.event_name == 'schedule'}}
  test:
    needs: setup
    strategy:
      fail-fast: false
      matrix: 
        include: ${{fromJSON(needs.setup.outputs.packages)}}
    name: ${{matrix.displayName}}
    runs-on: ${{matrix.params.runner}}
    env: ${{matrix.params.env}}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.params.node}}
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          working-directory: ${{matrix.path}}
          test-type: ${{(github.event_name == 'pull_request' && 'sanity') || github.event.inputs.test-type}}
          build-type: ${{github.event.inputs.build-type}}
          setup-type: ${{github.event.inputs.setup-type}}
          links: ${{matrix.params.links || github.event.inputs.links}}
          grep: ${{github.event.inputs.grep}}
        env:
          APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
          APPLITOOLS_API_KEY_READ: ${{secrets.APPLITOOLS_API_KEY_READ}}
          SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
          SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
          BROWSERSTACK_USERNAME: applitools
          BROWSERSTACK_ACCESS_KEY: ${{secrets.BROWSERSTACK_ACCESS_KEY}}
      - name: Report
        if: always()
        uses: ./.github/actions/report
        with:
          paths: |
            ${{matrix.path}}/logs/report.json
      - name: Save testing artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-${{matrix.name}}
          retention-days: 2
          if-no-files-found: ignore
          path: |
            ${{matrix.path}}/logs/**/*
