name: Test2 - sdk storybook

on:
  workflow_dispatch:
    inputs:
      for_versions:
        description: Storybook version
        type: choice
        options: ['all', '6.4.0', '5.0.0']
        default: 'all'
        required: true
env:
  PACKAGE_DIR: eyes-storybook
  FORCE_COLOR: 3
  STDOUT_LEVEL: 1
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
  APPLITOOLS_API_KEY_SDK: ${{secrets.APPLITOOLS_API_KEY_SDK}}
  APPLITOOLS_API_KEY_READ: ${{secrets.APPLITOOLS_API_KEY_READ}}
jobs:
  test:
    strategy:
      max-parallel: 3
      matrix:
        storybook-version: ['6.4.0', '5.0.0']
    name: 'Test (Storybook version: ${{matrix.storybook-version}})'
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          package: ${{env.PACKAGE_DIR}}
        env:
          STORYBOOK_VERSION: ${{matrix.storybook-version}}
